spring:
  datasource:
    url: jdbc:mysql://database-1.cjkwcw2kg0w4.ap-northeast-2.rds.amazonaws.com:3306/PTTrainer
    username: admin
    password: WOfkr159.
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000